name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Cordova
      run: |
        npm install -g cordova@latest
        cordova -v

    - name: Create Cordova project
      run: |
        cordova create smartgo-app com.smartgo.bus "SmartGo智能公交"

    - name: Copy project files
      run: |
        cp phonegap-build/config.xml smartgo-app/config.xml
        cp -r phonegap-build/www/* smartgo-app/www/

    - name: Add Android platform and build
      run: |
        cd smartgo-app
        cordova platform add android --save
        cordova requirements
        cordova build android --debug --verbose

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: smartgo-bus-debug
        path: smartgo-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: smartgo-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
